# Generated by Django 6.0.1 on 2026-01-19 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_budget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Pago'), ('CANCELLED', 'Cancelado')], default='PAID', max_length=10, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Método')),
                ('type', models.CharField(choices=[('CASH', 'Dinheiro'), ('DEBIT', 'Débito'), ('CREDIT', 'Crédito'), ('PIX', 'PIX'), ('TRANSFER', 'Transferência'), ('BOLETO', 'Boleto')], max_length=10, verbose_name='Tipo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.paymentmethod', verbose_name='Método de Pagamento'),
        ),
    ]
