# Generated by Django 6.0.1 on 2026-01-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_transaction_status_paymentmethod_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_paid',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Dinheiro'), ('DEBIT', 'Cartão de Débito'), ('CREDIT', 'Cartão de Crédito'), ('PIX', 'PIX'), ('TRANSFER', 'Transferência'), ('BOLETO', 'Boleto'), ('OTHER', 'Outro')], default='CASH', max_length=10, verbose_name='Método de Pagamento'),
        ),
    ]
