# Generated by Django 6.0.1 on 2026-01-19 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_remove_transaction_is_paid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('type', models.CharField(choices=[('EXPENSE', 'Despesa'), ('INCOME', 'Receita')], max_length=7, verbose_name='Tipo')),
                ('payment_method', models.CharField(choices=[('CASH', 'Dinheiro'), ('DEBIT', 'Cartão de Débito'), ('CREDIT', 'Cartão de Crédito'), ('PIX', 'PIX'), ('TRANSFER', 'Transferência'), ('BOLETO', 'Boleto'), ('OTHER', 'Outro')], max_length=10, verbose_name='Método de Pagamento')),
                ('frequency', models.CharField(choices=[('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensal'), ('YEARLY', 'Anual')], default='MONTHLY', max_length=10, verbose_name='Frequência')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Término (Opcional)')),
                ('last_generated_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transação Recorrente',
                'verbose_name_plural': 'Transações Recorrentes',
            },
        ),
    ]
